# Generated by Django 3.0.2 on 2020-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_development_indicators_backend', '0002_auto_20200126_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='data_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='indicator_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1960',
            field=models.CharField(blank=True, db_column='1960', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1961',
            field=models.CharField(blank=True, db_column='1961', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1962',
            field=models.CharField(blank=True, db_column='1962', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1963',
            field=models.CharField(blank=True, db_column='1963', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1964',
            field=models.CharField(blank=True, db_column='1964', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1965',
            field=models.CharField(blank=True, db_column='1965', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1966',
            field=models.CharField(blank=True, db_column='1966', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1967',
            field=models.CharField(blank=True, db_column='1967', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1968',
            field=models.CharField(blank=True, db_column='1968', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1969',
            field=models.CharField(blank=True, db_column='1969', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1970',
            field=models.CharField(blank=True, db_column='1970', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1971',
            field=models.CharField(blank=True, db_column='1971', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1972',
            field=models.CharField(blank=True, db_column='1972', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1973',
            field=models.CharField(blank=True, db_column='1973', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1974',
            field=models.CharField(blank=True, db_column='1974', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1975',
            field=models.CharField(blank=True, db_column='1975', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1976',
            field=models.CharField(blank=True, db_column='1976', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1977',
            field=models.CharField(blank=True, db_column='1977', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1978',
            field=models.CharField(blank=True, db_column='1978', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1979',
            field=models.CharField(blank=True, db_column='1979', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1980',
            field=models.CharField(blank=True, db_column='1980', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1981',
            field=models.CharField(blank=True, db_column='1981', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1982',
            field=models.CharField(blank=True, db_column='1982', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1983',
            field=models.CharField(blank=True, db_column='1983', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1984',
            field=models.CharField(blank=True, db_column='1984', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1985',
            field=models.CharField(blank=True, db_column='1985', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1986',
            field=models.CharField(blank=True, db_column='1986', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1987',
            field=models.CharField(blank=True, db_column='1987', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1988',
            field=models.CharField(blank=True, db_column='1988', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1989',
            field=models.CharField(blank=True, db_column='1989', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1990',
            field=models.CharField(blank=True, db_column='1990', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1991',
            field=models.CharField(blank=True, db_column='1991', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1992',
            field=models.CharField(blank=True, db_column='1992', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1993',
            field=models.CharField(blank=True, db_column='1993', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1994',
            field=models.CharField(blank=True, db_column='1994', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1995',
            field=models.CharField(blank=True, db_column='1995', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1996',
            field=models.CharField(blank=True, db_column='1996', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1997',
            field=models.CharField(blank=True, db_column='1997', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1998',
            field=models.CharField(blank=True, db_column='1998', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_1999',
            field=models.CharField(blank=True, db_column='1999', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2000',
            field=models.CharField(blank=True, db_column='2000', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2001',
            field=models.CharField(blank=True, db_column='2001', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2002',
            field=models.CharField(blank=True, db_column='2002', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2003',
            field=models.CharField(blank=True, db_column='2003', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2004',
            field=models.CharField(blank=True, db_column='2004', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2005',
            field=models.CharField(blank=True, db_column='2005', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2006',
            field=models.CharField(blank=True, db_column='2006', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2007',
            field=models.CharField(blank=True, db_column='2007', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2008',
            field=models.CharField(blank=True, db_column='2008', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2009',
            field=models.CharField(blank=True, db_column='2009', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2010',
            field=models.CharField(blank=True, db_column='2010', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2011',
            field=models.CharField(blank=True, db_column='2011', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2012',
            field=models.CharField(blank=True, db_column='2012', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2013',
            field=models.CharField(blank=True, db_column='2013', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2014',
            field=models.CharField(blank=True, db_column='2014', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2015',
            field=models.CharField(blank=True, db_column='2015', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2016',
            field=models.CharField(blank=True, db_column='2016', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2017',
            field=models.CharField(blank=True, db_column='2017', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2018',
            field=models.CharField(blank=True, db_column='2018', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2019',
            field=models.CharField(blank=True, db_column='2019', max_length=50),
        ),
        migrations.AlterField(
            model_name='worlddevelopmentindicators',
            name='y_2020',
            field=models.CharField(blank=True, db_column='2020', max_length=50),
        ),
    ]
